import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner/Banner.component";
import Navbar from "../components/navbar/Navbar.component";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          title="House of Dragons"
          subtitle="new awesome movie"
          imageUrl="https://www.hollywoodreporter.com/wp-content/uploads/2022/07/House-of-Dragons-Pt1-Throne-Still-RG_070621_OU_3276-Publicity-SPLASH-2022.jpg?w=1440&h=810&crop=1&resize=1500%2C845"
        />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
